[ADD] 회원가입 기능 추가
wecode-bootcamp-korea/29-1st-BAMIN-SURVIVAL-backend pull request #1
Opened 2022-01-24 12:04 UTC by sosolyht

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원가입 기능 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입시 bcrypt 를 이용해 암호화
2. 정규식으로 패스워드와 이메일에 예외처리를 했어야하지만 깜빡했습니다. (푸쉬예정 :( )

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 기존에 했던 기능이라 아직까지는 어려운점 없이 했습니다.

<br />

## :: 기타 질문 및 특이 사항
- 컨벤션 적용을 못했습니다. 다음 푸쉬때 수정해서 커밋하겠습니다.

2022-01-25 04:34 UTC, JHYUNNY reviewed
잘하셨습니다 ^.^

2022-01-25 04:34 UTC, JHYUNNY commented on users/models.py
> +    account        = models.CharField(max_length=50)
깔끔하네요 !! 혹시 id 대신 account 로 쓴 이유가 있을까요? - 아까 오전에 확인!

2022-01-25 04:59 UTC, sosolyht commented on users/models.py
> +    account        = models.CharField(max_length=50)
생각해보니 id 도 괜찮은것 같긴한데 멋있어보이려고 account 로 썻네요 
id 로 바꾸겠습니다.

2022-01-25 05:20 UTC, sosolyht commented on users/models.py
> +    account        = models.CharField(max_length=50)
그대로 account 로 진행하기로했습니다.

2022-01-26 02:23 UTC, bigfanoftim requested changes
그리고 회원가입 기능이기 때문에 db modeling은 따로 올려주셔야 합니다. 우선 기능에 대한 리뷰만 작성했습니다! 모델링 PR 먼저 올려주세요~

2022-01-26 02:23 UTC, bigfanoftim commented on users/validator.py
> +def is_password(password):
`is_password` 보다 `password_validation`이 더 나을것 같습니다. 단순히 비밀번호인지 판단하는게 아니라 비밀번호의 정규표현식을 검증하는 함수기 때문입니다.
```suggestion
def password_validation(password):
```

2022-01-26 02:23 UTC, bigfanoftim commented on users/validator.py
> +def is_email(email):
위와 같은 이유로 수정해주세요.
```suggestion
def email_validation(email):
```

2022-01-26 02:23 UTC, bigfanoftim commented on users/views.py
> +from django.views import View
```suggestion
from django.http  import JsonResponse
from django.views import View
```

2022-01-26 02:23 UTC, bigfanoftim commented on users/views.py
> +from users.validator import *
`*`로 모든 것을 다 불러오는 것은 최대한 삼가해주세요. 이후에 validator가 추가될 경우 불필요한 import가 될 수 있습니다.
```suggestion
from users.models    import User
from users.validator import email_validation, password_validation
```

2022-01-27 05:47 UTC, merged