[29기 최희택] 모델 리팩토링
wecode-bootcamp-korea/29-1st-BAMIN-SURVIVAL-backend pull request #25
Opened 2022-02-07 09:17 UTC by sosolyht

[fix] migrations

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-02-08 05:22 UTC, bigfanoftim requested changes

2022-02-08 05:22 UTC, bigfanoftim commented on cart/models.py
> +    product_options = models.ForeignKey(ProductOption, on_delete = models.CASCADE)
```suggestion
    user           = models.ForeignKey(User, on_delete = models.CASCADE)
    product_option = models.ForeignKey(ProductOption, on_delete = models.CASCADE)
```

2022-02-08 05:22 UTC, bigfanoftim commented on products/models.py
>      product        = models.ForeignKey('Product', on_delete = models.CASCADE)
```suggestion
class ProductImage(Base):
    img_url        = models.URLField(max_length = 200)
    detail_img_url = models.URLField(max_length = 200)
    product        = models.ForeignKey('Product', on_delete = models.CASCADE)
    
    class Meta:
        db_table = 'product_images'
    
class SlideImage(Base):
    image_url = models....
    # is_activated = models.Boolean
    priority = models.PositiveIntegerField(...)
    
    class Meta:
        db_table = 'slide_images'
```

2022-02-08 07:22 UTC, sosolyht commented on cart/models.py
> +    product_options = models.ForeignKey(ProductOption, on_delete = models.CASCADE)
완료했습니다

2022-02-08 09:16 UTC, bigfanoftim requested changes
DB modeling 과 관련된 코드만 올려주세요!

2022-02-08 10:07 UTC, sosolyht commented
> DB modeling 과 관련된 코드만 올려주세요!

수정완료하였습니다!

2022-02-09 01:14 UTC, bigfanoftim approved these changes
LGTM 👍

2022-02-09 01:14 UTC, merged