[최희택] users 모델링
wecode-bootcamp-korea/29-1st-BAMIN-SURVIVAL-backend pull request #3
Opened 2022-01-26 05:16 UTC by sosolyht

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- users 모델링
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입 기능 추가

<br />

## :: 기타 질문 및 특이 사항
- feature/signup 에서 feature/modeling 으로 checkout 하여 그대로 push 하였습니다

2022-01-26 06:06 UTC, bigfanoftim commented
희택님! 모델링 잘 작성해주셨습니다! 하지만 모델링 PR이니 나머지 수정사항들은 다른 PR로 올려주세요! 기능별로 나눠서 여러개의 PR로 작성해주세요.

- 모델링 PR
- validator PR
- SignUp PR
- SignIn PR

2022-01-26 14:17 UTC, lordmyshepherd requested changes

2022-01-26 14:17 UTC, lordmyshepherd commented on products/models.py
> +class ProductOptions(Base):
1. class명은 단수로 만들어주세요~
2. 테이블 명을 아래와 같이 직접 만들어주세요~

```suggestion
class ProductOption(Base):
    class Meta:
        db_table = 'product_options'
```

2022-01-26 14:17 UTC, lordmyshepherd commented on products/models.py
> +class Product(Base):
위에 피드백과 동일 합니다.

2022-01-27 01:03 UTC, sosolyht commented on products/models.py
> +class ProductOptions(Base):
수정하였습니다 !

2022-01-27 01:03 UTC, sosolyht commented on products/models.py
> +class Product(Base):
수정하였습니다 !

2022-01-27 02:32 UTC, bigfanoftim requested changes

2022-01-27 02:32 UTC, bigfanoftim commented on orders/models.py
> +    class Meta:
어떤 유저의 주문인지 알 수 있어야 할 것 같아요 희택님!
```suggestion
class Order(Base):
    order_number = models.IntegerField()
    user         = models.ForeignKey('users.User', ```)

    class Meta:
```

2022-01-27 03:49 UTC, sosolyht commented on orders/models.py
> +    class Meta:
수정하겠습니다!

2022-01-27 05:47 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-01-27 05:47 UTC, merged